-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [1] = {
        ["name"] = "WScreen<1>",
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["switchto"] = true,
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["name"] = "WFrame<4>",
                                    ["type"] = "WFrame",
                                    ["managed"] = {
                                        [1] = {
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["geom"] = {
                                                        ["h"] = 1178,
                                                        ["w"] = 958,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 4,
                                                    ["windowid"] = 16777217,
                                                    ["sizepolicy"] = "full",
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["type"] = "WGroupCW",
                                            ["geom"] = {
                                                ["h"] = 1178,
                                                ["w"] = 958,
                                                ["x"] = 1,
                                                ["y"] = 21,
                                            },
                                            ["level"] = 0,
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<2>",
                                        },
                                    },
                                },
                            },
                            ["tls"] = 960,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "horizontal",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["name"] = "WFrame",
                                    ["type"] = "WFrame",
                                    ["managed"] = {
                                        [1] = {
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["geom"] = {
                                                        ["h"] = 1173,
                                                        ["w"] = 956,
                                                        ["x"] = 1,
                                                        ["y"] = 3,
                                                    },
                                                    ["checkcode"] = 3,
                                                    ["windowid"] = 10486576,
                                                    ["sizepolicy"] = "full",
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["type"] = "WGroupCW",
                                            ["geom"] = {
                                                ["h"] = 1178,
                                                ["w"] = 958,
                                                ["x"] = 1,
                                                ["y"] = 21,
                                            },
                                            ["level"] = 0,
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<1>",
                                        },
                                    },
                                },
                            },
                            ["brs"] = 960,
                        },
                        ["name"] = "WTiling<2>",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["h"] = 1200,
                            ["w"] = 1920,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["bottom"] = true,
                    },
                },
                ["type"] = "WGroupWS",
                ["geom"] = {
                    ["h"] = 1200,
                    ["w"] = 1920,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["level"] = 0,
                ["initial_outputs"] = {
                    [1] = "VGA1",
                },
                ["sizepolicy"] = "full",
                ["name"] = "WGroupWS<2>",
            },
            [2] = {
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["geom"] = {
                            ["h"] = 480,
                            ["w"] = 640,
                            ["x"] = 640,
                            ["y"] = 360,
                        },
                        ["level"] = 1025,
                        ["bottom"] = true,
                        ["sizepolicy"] = "free_glue",
                        ["name"] = "*scratchpad*",
                    },
                },
                ["geom"] = {
                    ["h"] = 1200,
                    ["w"] = 1920,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["unnumbered"] = true,
                ["hidden"] = true,
                ["name"] = "*scratchws*",
                ["initial_outputs"] = {
                },
                ["level"] = 1,
                ["pseudomodal"] = true,
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
            },
            [3] = {
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["geom"] = {
                            ["h"] = 480,
                            ["w"] = 640,
                            ["x"] = 640,
                            ["y"] = 360,
                        },
                        ["level"] = 1025,
                        ["bottom"] = true,
                        ["sizepolicy"] = "free_glue",
                        ["name"] = "*scratchpad*<2>",
                    },
                },
                ["geom"] = {
                    ["h"] = 1200,
                    ["w"] = 1920,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["unnumbered"] = true,
                ["hidden"] = true,
                ["name"] = "*scratchws*<2>",
                ["initial_outputs"] = {
                },
                ["level"] = 1,
                ["pseudomodal"] = true,
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
            },
            [4] = {
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["geom"] = {
                            ["h"] = 480,
                            ["w"] = 640,
                            ["x"] = 640,
                            ["y"] = 360,
                        },
                        ["level"] = 1025,
                        ["bottom"] = true,
                        ["sizepolicy"] = "free_glue",
                        ["name"] = "*scratchpad*<3>",
                    },
                },
                ["geom"] = {
                    ["h"] = 1200,
                    ["w"] = 1920,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["unnumbered"] = true,
                ["hidden"] = true,
                ["name"] = "*scratchws*<3>",
                ["initial_outputs"] = {
                },
                ["level"] = 1,
                ["pseudomodal"] = true,
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
            },
        },
    },
    [0] = {
        ["name"] = "WScreen",
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["name"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tls"] = 1905,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["name"] = "WFrame<1>",
                                    ["type"] = "WFrame",
                                    ["managed"] = {
                                    },
                                },
                            },
                            ["brs"] = 15,
                        },
                        ["name"] = "WTiling",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["h"] = 1920,
                            ["w"] = 1200,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["bottom"] = true,
                    },
                },
                ["type"] = "WGroupWS",
                ["geom"] = {
                    ["h"] = 1920,
                    ["w"] = 1200,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["level"] = 0,
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["sizepolicy"] = "full",
                ["hidden"] = true,
            },
            [2] = {
                ["switchto"] = true,
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tls"] = 1905,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["name"] = "WFrame<3>",
                                    ["type"] = "WFrame",
                                    ["managed"] = {
                                        [1] = {
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["geom"] = {
                                                        ["h"] = 1870,
                                                        ["w"] = 1196,
                                                        ["x"] = 1,
                                                        ["y"] = 6,
                                                    },
                                                    ["checkcode"] = 1,
                                                    ["windowid"] = 10497190,
                                                    ["sizepolicy"] = "full",
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["type"] = "WGroupCW",
                                            ["geom"] = {
                                                ["h"] = 1883,
                                                ["w"] = 1198,
                                                ["x"] = 1,
                                                ["y"] = 21,
                                            },
                                            ["level"] = 0,
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<3>",
                                        },
                                    },
                                },
                            },
                            ["brs"] = 15,
                        },
                        ["name"] = "WTiling<1>",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["h"] = 1920,
                            ["w"] = 1200,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["bottom"] = true,
                    },
                },
                ["type"] = "WGroupWS",
                ["geom"] = {
                    ["h"] = 1920,
                    ["w"] = 1200,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["level"] = 0,
                ["initial_outputs"] = {
                    [1] = "HDMI1",
                },
                ["sizepolicy"] = "full",
                ["name"] = "WGroupWS<1>",
            },
            [3] = {
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WClientWin",
                        ["geom"] = {
                            ["h"] = 1920,
                            ["w"] = 1200,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["checkcode"] = 2,
                        ["windowid"] = 10485767,
                        ["sizepolicy"] = "full",
                        ["level"] = 1,
                    },
                },
                ["type"] = "WGroupCW",
                ["geom"] = {
                    ["h"] = 1920,
                    ["w"] = 1200,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["level"] = 0,
                ["name"] = "WGroupCW",
                ["sizepolicy"] = "full",
                ["hidden"] = true,
            },
            [4] = {
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["geom"] = {
                            ["h"] = 480,
                            ["w"] = 640,
                            ["x"] = 363,
                            ["y"] = 144,
                        },
                        ["level"] = 1025,
                        ["bottom"] = true,
                        ["sizepolicy"] = "free_glue",
                        ["name"] = "*scratchpad*<1>",
                    },
                },
                ["geom"] = {
                    ["h"] = 1920,
                    ["w"] = 1200,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["unnumbered"] = true,
                ["hidden"] = true,
                ["name"] = "*scratchws*<1>",
                ["initial_outputs"] = {
                },
                ["level"] = 1,
                ["pseudomodal"] = true,
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
            },
        },
    },
}

