-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/restart",
    [2] = "lua:META='Mod3+'",
    [3] = "man:",
    [4] = "yesno:yes",
    [5] = "menu.mainmenu:styles/look_newviolet",
    [6] = "yesno:no",
    [7] = "menu.mainmenu:styles/look_dusky",
    [8] = "run:chromium-browser",
    [9] = "menu.mainmenu:session/exit",
}

