set nocompatible               " be iMproved
filetype off                   " required for vundle!

" Vundle
" Vundle install :  $ git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle " required!
Bundle 'gmarik/vundle'

" colorscheme
Bundle 'fmoralesc/vim-vitamins.git'
" syntax hl
Bundle 'mako.vim'
Bundle 'Jinja'
Bundle 'vim-coffee-script'
Bundle 'saltstack/salt-vim'


" python
"Bundle 'pyflakes.vim'
"Bundle 'scrooloose/syntastic'
Bundle 'indentpython.vim'
"Bundle 'davidhalter/jedi-vim'
" Others
"Bundle 'git://git.wincent.com/command-t.git'
Bundle 'The-NERD-Commenter'
Bundle 'lambdatoast/elm.vim'
"Bundle 'taglist.vim'
Bundle 'Tagbar'
Bundle 'kien/ctrlp.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-repeat'
" Allow pressing -
Bundle 'tpope/vim-vinegar'
" Allow :SudoWrite
Bundle 'tpope/vim-eunuch'
Bundle 'PeterRincker/vim-argumentative'
Bundle 'airblade/vim-gitgutter'
Bundle 'Yggdroot/indentLine'
Bundle 'vim-airline/vim-airline'
Bundle 'vim-airline/vim-airline-themes'
" see bellow for activation
"Bundle 'kien/rainbow_parentheses.vim'


Bundle 'dbeniamine/todo.txt-vim.git'
Bundle 'chrisbra/recover.vim'



Bundle 'kana/vim-textobj-user'
Bundle 'bps/vim-textobj-python'

"Bundle 'vimez/vim-showmarks' " conflict with vim-gutter, deactivated
" Snipmate & dependencies
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
"Bundle "honza/snipmate-snippets"
Bundle "garbas/vim-snipmate"
"Bundle 'file:///home/olivier/Projects/openerp-snippets.vim/'
" End snipmate
Bundle 'moll/vim-bbye'

Bundle 'vimwiki/vimwiki'

set rtp+=~/.fzf

filetype plugin indent on     " required for vundle!
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..

" more colors
set t_Co=256

" syntax hl
syntax on

" mouse for when I'm lazy
set mouse=a

set nosmartindent
set smarttab
set et
set sw=4
set ts=4
set softtabstop=4
set hidden

set hlsearch
set list
set listchars=tab:▸\ ,extends:❯,precedes:❮,trail:·
",eol:¬



" Resize splits when the window is resized
au VimResized * :wincmd =

" Fold javascript
"let javaScript_fold=1

" Some shortcuts
map <C-c> :confirm qa<cr>
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
map <F5> :TagbarToggle<cr>
nmap ; :
nnoremap <Leader>o :CtrlP<CR>
nnoremap <Leader>w :w<CR>
map q: :q


colorscheme vitamins

" Shortcut to reload snippets
noremap <silent><F6> :call ResetSnippets()<CR>:call " GetSnippets(snippets_dir, &ft)<CR>

" Ignore theses extensions
set suffixes=*.pyc,*.aux,*.swp,*.pyo,*.arm
set wildignore=*.swp,*.pyc,*.arm

" Shortcut for Autopep
noremap ,a :up<cr>:silent !autopep8  --max-line-length=80 -i %<cr>:e!<cr>:redraw!<cr>
noremap ,b :up<cr>:silent !pyfmt -i %<cr>:e!<cr>:redraw!<cr>

" Some auto filetype detection for color syntaxing
au BufNewFile,BufRead *.mako setfiletype mako
au BufRead,BufNewFile *.go setfiletype go
au BufRead,BufNewFile *.coffee set ts=4 sw=4
autocmd FileType netrw nnoremap q :bp\|bd #<CR>
autocmd BufRead,BufNewFile *.c set noet

nmap <C-n> :bnext<CR>
nmap <C-p> :bprev<CR>

" for https://github.com/kien/rainbow_parentheses.vim
"au VimEnter * RainbowParenthesesToggle
"au Syntax * RainbowParenthesesLoadRound
"au Syntax * RainbowParenthesesLoadSquare
"au Syntax * RainbowParenthesesLoadBraces

" syntastic
let g:airline#extensions#syntastic#enabled = 1

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

nmap =- <Plug>VimwikiRemoveHeaderLevel
cnoremap help vert help
map <Leader>s :SyntasticToggleMode<CR>


" For todo.txt
map <Leader>t :e Dropbox/1 GTD/todo.txt<CR>
let g:Todo_txt_prefix_creation_date=1
" map \r to XWindows clipboard
map <Leader>r "+gp
" Following is necessary because from my testing xdg-open don't work from
" gvim, to remove when this is fixed
if has('gui_running')
    let g:netrw_browsex_viewer='firefox'
endif

" err needed for gdiff
set diffopt+=vertical
