set nocompatible               " be iMproved
filetype off                   " required for vundle!

" Vundle
" Vundle install :  $ git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle " required!
Bundle 'gmarik/vundle'

" colorscheme
Bundle 'fmoralesc/vim-vitamins.git'
" syntax hl
Bundle 'mako.vim'
Bundle 'Jinja'
Bundle 'vim-coffee-script'
Bundle 'saltstack/salt-vim'


" python
Bundle 'pyflakes.vim'
Bundle 'indentpython.vim'
Bundle 'davidhalter/jedi-vim'
" Others
Bundle 'git://git.wincent.com/command-t.git'
Bundle 'The-NERD-Commenter'
Bundle 'lambdatoast/elm.vim'
"Bundle 'taglist.vim'
Bundle 'Tagbar'
Bundle 'kien/ctrlp.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-vinegar'
Bundle 'PeterRincker/vim-argumentative'
Bundle 'airblade/vim-gitgutter'
Bundle 'Yggdroot/indentLine'
"Bundle 'vimez/vim-showmarks' " conflict with vim-gutter, deactivated
" Snipmate & dependencies
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
"Bundle "honza/snipmate-snippets"
Bundle "garbas/vim-snipmate"
Bundle 'file:///home/olivier/Projects/openerp-snippets.vim/'
" End snipmate
Bundle 'moll/vim-bbye'

set rtp+=~/.fzf

filetype plugin indent on     " required for vundle!
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..

" Some auto filetype detection for color syntaxing
au BufNewFile,BufRead *.mako setfiletype mako
au BufRead,BufNewFile *.go setfiletype go
au BufRead,BufNewFile *.coffee set ts=4 sw=4

" more colors
set t_Co=256

" syntax hl
syntax on

" mouse for when I'm lazy
set mouse=a

set nosmartindent
set smarttab
set et
set sw=4
set ts=4
set softtabstop=4
set hidden

set hlsearch
set list
set listchars=tab:▸\ ,extends:❯,precedes:❮,trail:·
",eol:¬



" Resize splits when the window is resized
au VimResized * :wincmd =

" Fold javascript
"let javaScript_fold=1

" Some shortcuts
map <C-c> :confirm qa<cr>
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
map <F5> :TagbarToggle<cr>
nmap ; :
nnoremap <Leader>o :CtrlP<CR>
nnoremap <Leader>w :w<CR>
map q: :q


colorscheme vitamins

" Shortcut to reload snippets
noremap <silent><F6> :call ResetSnippets()<CR>:call " GetSnippets(snippets_dir, &ft)<CR>

" Ignore theses extensions
set suffixes=*.pyc,*.aux,*.swp,*.pyo
set wildignore=*.swp,*.pyc

" Shortcut for Autopep
noremap ,a :up<cr>:silent !autopep8  -i %<cr>:e!<cr>:redraw!<cr>
noremap ,b :up<cr>:silent !pyfmt -i %<cr>:e!<cr>:redraw!<cr>

autocmd FileType netrw nnoremap q :bp\|bd #<CR>

nmap <C-n> :bnext<CR>
nmap <C-p> :bprev<CR>

