# Created by newuser for 4.3.17
fpath=(~/.zsh/completion $fpath)

#source ~/Projects/zsh-git-prompt/zshrc.sh
#source ~/Projects/liquidprompt/liquidprompt
#source ~/zsh_dbmanagement
#fpath=($HOME/Projects/zsh-completions/src $fpath)
#PROMPT='%{'$'\033[01;32m%}%n@%B%m%{\033[00m%} %{\033[01;33m%}%~%{\033[00m%}%b$(git_super_status)%{\033[00m%} '
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}'
zstyle ':completion:*' max-errors 3 numeric
zstyle ':completion:*' use-compctl false
autoload -Uz compinit
compinit

setopt INC_APPEND_HISTORY
setopt histignorealldups sharehistory
# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history



# general
alias ls='ls --color=auto'
alias o="xdg-open"
alias reload="source ~/.zshrc"

alias bstart="bluetile & chromium & tomboy & nm-applet & feh --bg-center 43Ip0Ww.jpg "
alias pgactivity="pg_activity -h \"\""
alias pga="pg_activity -h \"\""

# Work
alias os="/home/olivier/.virtualenvs/rn/bin/python /home/olivier/Projects/openerp-server/bin/openerp-server.py --log-level=test --without-demo=all"
alias ow="/home/olivier/.virtualenvs/rn/bin/python /home/olivier/Projects/openerp-web/openerp-web.py"

alias prod="echo -en \"\033]0;prod\a\"; ssh openerp@donut.railnova.eu -t screen -RD;echo -en \"\033]0;Terminal\a\"; "
alias atunnel="ssh olivier@donut.railnova.eu -L 6540:localhost:443"


# Needed for virtual env
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects #used by mkproject (of virtualenvwrapper)
#source /etc/bash_completion.d/virtualenvwrapper
source /usr/share/virtualenvwrapper/virtualenvwrapper_lazy.sh


# ANTIGEN
source $HOME/dotfiles/antigen.zsh
#antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle nojhan/liquidprompt
antigen bundle zsh-users/zsh-completions src
antigen apply


vmr()
{
    echo -en "\033]0;$1\a"
    ssh speculos -tA ssh -t $1 sudo screen -RD $2
    echo -en "\033]0;out\a"
}

vm()
{
    echo -en "\033]0;$1\a"
    ssh speculos -tA ssh -t $1 screen -RD
    echo -en "\033]0;out\a"
}

alias c="cd .."
alias m="python manage.py"
alias nb="echo -en \"\033]0;Notebook serv\a\";~/.virtualenvs/nb/bin/ipython notebook --profile=nb;echo -en \"\033]0;out\a\";"
alias rnb="echo -en \"\033]0;Notebook serv\a\";~/.virtualenvs/rn/bin/ipython notebook --profile=nb;echo -en \"\033]0;out\a\";"
alias gnb="echo -en \"\033]0;Notebook serv\a\";~/.virtualenvs/ng/bin/ipython notebook --profile=gnb;echo -en \"\033]0;out\a\";"
alias as="apt-cache search"
alias ai="sudo apt-get install"
# Insert Google DNS in resolv.conf
alias gdns="sudo sh -c 'echo nameserver 8.8.8.8 > /etc/resolv.conf'"


# set up PIP Download cache so it won't reload the package
export PIP_DOWNLOAD_CACHE=$HOME/.cache/pip
# Command to release on pypi
alias release="python setup.py egg_info sdist bdist_wheel bdist_egg upload"

# Taken from debian default .zsh not sure what it does yet
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# ng dev
alias fakesmtp="/usr/bin/python -m smtpd -n -c DebuggingServer localhost:4025"
alias fakestation="/home/olivier/.virtualenvs/station/bin/python Projects/rn/station/manage.py runserver 8001"
alias ng="/home/olivier/.virtualenvs/sr/bin/python /home/olivier/Projects/RailfleetNG/manage.py"
alias sn="/home/olivier/.virtualenvs/su/bin/python /home/olivier/Projects/Supernova/manage.py"
alias snr="/home/olivier/.virtualenvs/sn/bin/python /home/olivier/Projects/Supernova/manage.py runserver 8001"
alias dbsize="psql postgres -c \"select datname, pg_size_pretty(pg_database_size(datname)) as size from pg_database order by pg_database_size(datname) desc;\""

# vpn
alias vpn="sudo openvpn ~/.rn-vpn.conf"


retrievedb() {
    lftp -c "open sftp://bkp@sabayon.railnova.eu; get bkp@donut.railnova.eu/$1/DAILY/LAST.dump -o ~/Projects/dumps/$1-$(date -I).dump"
}


dbrestore() {
    pg_restore -d postgres --create -x -O  $1

}
export PATH=$PATH:/home/olivier/.cabal/bin:/home/olivier/.local/bin

alias invoke="invoker ~/all.ini"

alias irc="echo -en \"\033]0;chat\a\"; ssh staz@server.staz.be -t screen -RDU pts-7; echo -en \"\033]0;Terminal\a\""
alias q="echo -en \"\033]0;/tmp/q\a\"; touch /tmp/q; tail -f /tmp/q; echo -en \"\033]0;Terminal\a\""

gcm() {
#    git commit -m "[$1] $(echo $*)";}
    git commit -m "$(echo $*)";}


export EDITOR=vim
alias autube="youtube-dl -x"
alias l="ls -lh"
alias taupe="netstat -taupe"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


cdp () {
    cd "$(python -c "import os.path as _, ${1}; \
            print(_.dirname(_.realpath(${1}.__file__[:-1])))"
        )"
}

fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

#alias git=hub
alias dbpwreset="psql -c \"update res_users set password ='admin';\""

alias shell='sudo -u django /home/django/Supernova/venv/bin/python /home/django/Supernova/manage.py shell_plus'
